//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RonSwanson_Quotes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RonSwansonQuotes_dbEntities : DbContext
    {
        public RonSwansonQuotes_dbEntities()
            : base("name=RonSwansonQuotes_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QuotesTable> QuotesTables { get; set; }
        public virtual DbSet<RatingsTable> RatingsTables { get; set; }
    }
}
